own_brands:
  - 百威
  - 哈尔滨
  - 科罗娜
  - 雪津

competitor_brands:
  - 青岛
  - 雪花
  - 乌苏
  - 喜力
  - RIO
  - 锐澳
  - 乐堡

aliases:
  百威: [百威, budweiser, bud]
  哈尔滨: [哈尔滨啤酒, 哈啤, harbinbeer]
  青岛: [青岛啤酒, 青啤, 崂山啤酒, 青岛纯生, 青岛1903, 青岛奥古特, 青岛原浆, 青岛崂山, 奥古特, 青岛白啤, tsingtaobeer]
  雪花: [雪花啤酒, 勇闯天涯, superx, snowbeer]
  乌苏: [乌苏 wusu, 红乌苏, 大乌苏, 夺命大乌苏]
  喜力: [heineken, 喜力, 海尼根]
  科罗娜: [corona, 科罗娜, 克罗那]
  雪津: [雪津, sedrin]
  RIO: [锐澳, RIO鸡尾酒, 锐澳鸡尾酒, rio微醺, rio强爽, 预调鸡尾酒]
